[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.install]
cmds = ['cd server && npm install', 'cd server && npx prisma generate']

[phases.build]
cmds = ['cd server && npx prisma db push', 'cd server && npm run build']

[start]
cmd = 'cd server && npm start'
